/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlansPricingRouteImport } from './routes/plans-pricing'
import { Route as HotelsRouteImport } from './routes/hotels'
import { Route as IndexRouteImport } from './routes/index'

const PlansPricingRoute = PlansPricingRouteImport.update({
  id: '/plans-pricing',
  path: '/plans-pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsRoute = HotelsRouteImport.update({
  id: '/hotels',
  path: '/hotels',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hotels': typeof HotelsRoute
  '/plans-pricing': typeof PlansPricingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hotels': typeof HotelsRoute
  '/plans-pricing': typeof PlansPricingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hotels': typeof HotelsRoute
  '/plans-pricing': typeof PlansPricingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/hotels' | '/plans-pricing'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/hotels' | '/plans-pricing'
  id: '__root__' | '/' | '/hotels' | '/plans-pricing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HotelsRoute: typeof HotelsRoute
  PlansPricingRoute: typeof PlansPricingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/plans-pricing': {
      id: '/plans-pricing'
      path: '/plans-pricing'
      fullPath: '/plans-pricing'
      preLoaderRoute: typeof PlansPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels': {
      id: '/hotels'
      path: '/hotels'
      fullPath: '/hotels'
      preLoaderRoute: typeof HotelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HotelsRoute: HotelsRoute,
  PlansPricingRoute: PlansPricingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
