/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlansPricingRouteImport } from './routes/plans-pricing'
import { Route as IndexRouteImport } from './routes/index'

const PlansPricingRoute = PlansPricingRouteImport.update({
  id: '/plans-pricing',
  path: '/plans-pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/plans-pricing': typeof PlansPricingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/plans-pricing': typeof PlansPricingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/plans-pricing': typeof PlansPricingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/plans-pricing'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/plans-pricing'
  id: '__root__' | '/' | '/plans-pricing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlansPricingRoute: typeof PlansPricingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/plans-pricing': {
      id: '/plans-pricing'
      path: '/plans-pricing'
      fullPath: '/plans-pricing'
      preLoaderRoute: typeof PlansPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlansPricingRoute: PlansPricingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
